server:
  port: 7081

#spring:
#  redis:
#    host: 192.168.117.222
#    database: 2
#    password: 123456

spring:
  redis:
    database: 2
    password: 123456
    sentinel:
      master: mymaster
      nodes:
        - 192.168.117.222:26381
        - 192.168.117.222:26382
        - 192.168.117.222:26383
    lettuce:
      pool:
        max-idle: 30   # ???????????
        max-total: 600   # ????????????????????
        min-idle: 8   # ???????????
    # 单机redis
    host: 192.16.8.76
logging:
  level:
    root: info
#    io.lettuce.core: debug
    org.springframework.data.redis: debug
