server:
  port: 7081

#spring:
#  redis:
#    host: 192.168.117.222
#    database: 2
#    password: 123456

spring:
  redis:
    database: 2
    password: 123456
    sentinel:
      master: mymaster
      nodes:
        - 192.16.8.201:26381
        - 192.16.8.201:26382
        - 192.16.8.201:26383
    lettuce:
      pool:
#        max-idle: 3   # 连接池中的最大空闲连接
#        max-active: 3   # 连接池最大连接数（使用负值表示没有限制）
#        min-idle: 3   # 连接池中的最小空闲连接
        max-idle: 30   # 连接池中的最大空闲连接
        max-active: 50   # 连接池最大连接数（使用负值表示没有限制）
        min-idle: 8   # 连接池中的最小空闲连接
    # 单机redis
    host: 192.16.8.76
    port: 6379



logging:
  level:
    root: info
#    io.lettuce.core: debug
    org.springframework.data.redis: debug
