server:
  port: 4848


spring:
  datasource:
    url: jdbc:mysql://test1.luckygames.dev:3306/bet_message?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&allowMultiQueries=true
    username: bet
    password: Gbank@lucky165
    driverClassName: com.mysql.cj.jdbc.Driver


mybatis:
  configuration:
    map-underscore-to-camel-case: true